image: node

cache:
  paths:
    - node_modules

before_script:
  - npm install --dev

stages:
  - build
  - deploy

buildNuxt:
  stage: build
  script:
    - npm run build
  artifacts:
    name: "client"
    paths:
      - public
  only: 
    - master

deployRelease:
  stage: deploy
  dependencies:
    - buildNuxt
  script:
    - apt-get update -qq && apt-get install -y -qq lftp
    - lftp "$LOGIN:$PASS@$URL:" mirror -R public/
  only: 
    - master
  when: manual
