image: node

stages:
  - build
  - deploy

extractLocale:
  stage: build
  cache:
    paths:
      - node_modules
  before_script:
    - npm install --dev
  script:
    - npm run extract
  artifacts:
    paths:
      - ru_extracted.json
  only:
    - develop

buildNuxt: 
  stage: build
  cache:
    paths:
      - node_modules
  before_script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/stereotech/misc/products-documentation.git docs
    - cd docs
    - node ./scripts/generate-menu.js
    - cd ..
    - cp -rf docs/static .
    - npm install --dev
  script:
    - npm run generate
  only: 
    - master
  artifacts:
    paths:
      - public

pages:
  stage: build
  cache:
    paths:
      - node_modules
  before_script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/stereotech/misc/products-documentation.git docs
    - cd docs
    - node ./scripts/generate-menu.js
    - cd ..
    - cp -rf docs/static .
    - npm install --dev
  script:
    - npm run generate:pages
  only:
    - develop


deployRelease:
  stage: deploy
  before_script:
    - apt-get update -qq && apt-get install -y -qq lftp
  script: 
    - lftp -e "set ftp:ssl-allow no; open $URL_EN; user $LOGIN_EN $PASS; mirror -parallel=10 -R public/ ./; bye"
  only: 
    - master