image: node

stages:
  - build
  - deploy

.buildNuxt: 
  stage: build
  cache:
    paths:
      - node_modules
  before_script:
    - mkdir .nuxt
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/stereotech/misc/products-documentation.git .nuxt/docs
    - cd .nuxt/docs
    - node ./scripts/generate-menu.js
    - cd ../..
    - cp -rf .nuxt/docs/static .nuxt
    - cp -rf .nuxt/docs/static .
    - npm install --dev
  artifacts:
    paths:
      - public

pages:
  extends: .buildNuxt
  script:
    - npm run generate
  only:
    - develop

buildNuxtRu:
  extends: .buildNuxt
  script:
    - npm run generate

buildNuxtEn:
  extends: .buildNuxt
  script:
    - npm run generate:en


.deployRelease:
  stage: deploy
  before_script:
    - apt-get update -qq && apt-get install -y -qq lftp
  only: 
    - master

deployReleaseRu:
  extends: .deployRelease
  needs: [buildNuxtRu]
  script:
    - lftp -e "set ftp:ssl-allow no; open $URL_RU; user $LOGIN_RU $PASS; mirror -X .* -X .*/ --reverse --verbose --delete dist/ ./; bye"

deployReleaseEn:
  extends: .deployRelease
  needs: [buildNuxtEn]
  script:
    - lftp -e "set ftp:ssl-allow no; open $URL_EN; user $LOGIN_EN $PASS; mirror -X .* -X .*/ --reverse --verbose --delete dist/ ./; bye"
